test

diff --git a/.github/workflows/check-changeset.yaml b/.github/workflows/check-changeset.yaml
--- a/.github/workflows/check-changeset.yaml
+++ b/.github/workflows/check-changeset.yaml
@@ -13,14 +13,23 @@ jobs:
       - name: Install Node.js and npm
         uses: actions/setup-node@v2
         with:
-          node-version: ">=18.0.0" # Specify a Node.js version compatible with your project
+          node-version: ">=18.0.0"
 
       - name: Install Dependencies
         run: npm install
 
       - name: Check for Changeset
         run: |
-          git fetch origin develop
-          git checkout develop
-          git pull origin develop
-          npx changeset status --since=develop
+          # Fetch changes from the pull request branch
+          git fetch origin ${{ github.head_ref }}
+          git checkout ${{ github.head_ref }}
+
+          # Check for changesets in the latest commit of the pull request
+          CHANGES=$(npx changeset status --since=${{ github.sha }})
+
+          if [ -z "$CHANGES" ]; then
+            echo "No changesets found in the latest commit of the pull request."
+            exit 1  # Fails the workflow
+          else
+            echo "Changesets found. Continuing with the workflow."
+          fi
