feat:test

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -3,7 +3,7 @@ name: CI
 on:
   pull_request:
     branches:
-      - develop
+      - main
 
 jobs:
   build:
@@ -24,6 +24,6 @@ jobs:
       - name: Check for Changeset
         run: npx changeset status --since=main
              if [ $? -eq 1 ]; then
-               echo "Error: No changeset found. This pull request cannot be merged without a changeset."
-               exit 1
+              echo "Error: No changeset found. This pull request cannot be merged without a changeset."
+              exit 1
              fi
